image: node:12.1.0

cache:
   key: ${CI_COMMIT_REF_SLUG}
   paths:
      - node_modules/
      - .next/cache/

stages:
   - setup
   - tests
   - build
   - deploy

setup:
   stage: setup
   script:
      - yarn install --frozen-lockfile

tests:
   stage: tests
   script:
      - yarn global add jest
      - yarn test

build:
   stage: build
   script:
      - yarn build
      - yarn export
   artifacts:
      paths:
         - out

.deploy_template: &deploy_template
   resource_group: deploy
   stage: deploy
   before_script:
      - yarn global add netlify-cli
   dependencies:
      - build
   only:
      - master

staging:
   <<: *deploy_template
   script:
      - netlify deploy --site $NETLIFY_SITE_ID_STAGING --auth $NETLIFY_AUTH_TOKEN --prod

production:
   <<: *deploy_template
   when: manual
   script:
      - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
