name: "Codacy Analysis"

on: ["push"]

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Codacy Analysis CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
